{ pkgs }:
let
  upstream = pkgs.fetchurl {
    url = "https://registry.npmjs.org/@material/material-color-utilities/-/material-color-utilities-0.4.0.tgz";
    hash = "sha256-Lwt1l0mEY1fdLZzg4dXoBx5bUb2iQXiz0kunWvp/cj0=";
  };
in
pkgs.runCommand "shelllist-material-colors-0.4.0"
  { nativeBuildInputs = [ pkgs.esbuild ]; }
  ''
    tar -xzf ${upstream}
    mkdir -p node_modules/@material "$out"
    mv package node_modules/@material/material-color-utilities
    cp ${../tools/material-colors.mjs} material-colors.mjs
    esbuild material-colors.mjs --bundle --format=iife --global-name=MaterialColors \
      --target=es2017 --legal-comments=inline \
      --banner:js='.pragma library
// Generated by nix/material-colors.nix; do not edit. Upstream: @material/material-color-utilities 0.4.0 (Apache-2.0).' \
      --outfile="$out/MaterialColors.generated.js"
    # JS var declarations already hoist. Make these two forward declarations
    # explicit for Qt's usedbeforedeclared analysis; initialization order stays
    # untouched. Do not suppress QML warnings or patch upstream color arithmetic.
    substituteInPlace "$out/MaterialColors.generated.js" \
      --replace-fail 'var MaterialColors = (() => {' 'var MaterialColors = (() => { var DynamicColor, KeyColor;' \
      --replace-fail 'var DynamicColor = class' 'DynamicColor = class' \
      --replace-fail 'var KeyColor = class' 'KeyColor = class'
    cp node_modules/@material/material-color-utilities/LICENSE "$out/material-color-utilities.LICENSE"
  ''
